### PR TITLE
add role id to types

### PR DESCRIPTION
**Pull request by Rexogamer**

### CODE REVIEW

**Comment by insertish** [comment]
Sorry for the delay, do we need this? Role Id is provided as a key in the roles object on the server as such is not on the role itself to not duplicate data.

**Comment by Rexogamer** [comment]
Oops - as for your question, I think I was unable to find the ID for a role or sorting? Not sure to be honest, will take another look

**Comment by insertish** [comment]
From the API documenation: [server object](https://developers.revolt.chat/api/#tag/Server-Information/paths/~1servers~1:server/get)

`roles` is an map / Record<String, Role>
The key is the role's ID.

Ordering is done using the rank number on Role object.

**Comment by Rexogamer** [comment]
something*, typo

i see - will close for now but we'll see

**Comment by Rexogamer** [comment]
Nope - taking another look, the Role object doesn't return an ID, which was the motivation for this PR. Here's my code - apologies if I'm missing something:
image

**Comment by insertish** [comment]
`server.roles` is an Record.

image

When you do `[0]`, `0` is treated as a key (not an index).
If you want to index into it for whatever reason, `Object.keys(server.roles)[0]`.

**Comment by Rexogamer** [comment]
Ahhhh, thank you. Closing as resolved.

**Pull request closed without merging**
